using System.Text;

namespace Waymark;

public sealed class InMemoryArtifactStore : IArtifactStore
{
    private readonly List<MigrationArtifact> _artifacts = [];

    public Task SaveAsync(MigrationArtifact artifact, CancellationToken cancellationToken = default)
    {
        cancellationToken.ThrowIfCancellationRequested();
        if (_artifacts.Any(existing => string.Equals(existing.MigrationId, artifact.MigrationId, StringComparison.Ordinal)))
        {
            throw new MigrationContractException($"Duplicate migration artifact '{artifact.MigrationId}'.");
        }

        if (_artifacts.Any(existing => existing.Provider != artifact.Provider || existing.DatabaseEngine != artifact.DatabaseEngine))
        {
            throw new MigrationContractException("An artifact store cannot contain multiple provider/database-engine identities.");
        }

        _artifacts.Add(artifact);
        return Task.CompletedTask;
    }

    public Task<IReadOnlyList<MigrationArtifact>> ReadAsync(
        ProviderId provider,
        DatabaseEngine databaseEngine,
        CancellationToken cancellationToken = default
    )
    {
        cancellationToken.ThrowIfCancellationRequested();
        var artifacts = MigrationArtifactRules.ValidateAndOrder(provider, databaseEngine, _artifacts);
        return Task.FromResult(artifacts);
    }
}

public sealed class SqlScriptComposer : IScriptComposer
{
    public string Compose(
        ProviderId provider,
        DatabaseEngine databaseEngine,
        IReadOnlyCollection<MigrationArtifact> artifacts
    )
    {
        var ordered = MigrationArtifactRules.ValidateAndOrder(provider, databaseEngine, artifacts);
        var builder = new StringBuilder();
        builder.AppendLine($"-- Generated by Waymark");
        builder.AppendLine($"-- Provider: {provider}");
        builder.AppendLine($"-- Database engine: {databaseEngine}");

        foreach (var artifact in ordered)
        {
            builder.AppendLine();
            builder.AppendLine($"-- Migration: {artifact.MigrationId}");
            builder.AppendLine(artifact.Payload);
        }

        return builder.ToString();
    }
}
