<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\Waymark\Waymark.csproj" />
    <ProjectReference Include="..\Providers\Waymark.MartenPostgres\Waymark.MartenPostgres.csproj" />
    <ProjectReference Include="..\Providers\Waymark.EFCoreSQLServer\Waymark.EFCoreSQLServer.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Spectre.Console.Cli" Version="0.52.1-preview.0.9" />
  </ItemGroup>

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
